E4BigSchool/ViewModels/CoursesViewModel.cs
using E4BigSchool.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace E4BigSchool.ViewModels
{
    public class CoursesViewModel
    {
        public IEnumerable<Course> UpcommingCourses { get; set; }
       
        public bool ShowAction { get; set; }
    }
}

E4BigSchool/Controllers/CoursesController.cs
using E4BigSchool.Models;
using E4BigSchool.ViewModel;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace E4BigSchool.Controllers
{
    
    public class CoursesController : Controller
    {
        private readonly ApplicationDbContext _dbcontext;

        public CoursesController()
        { 
            _dbcontext = new ApplicationDbContext() ;
         }
        public ActionResult Create()
        {
            var viewModel = new CourseViewModel
            {
                Categories = _dbcontext.Categories.ToList()
            };
            return View(viewModel);
        }


        // GET: Courses
        [Authorize]
        [HttpPost]
        public ActionResult Create(CourseViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                viewModel.Categories = _dbcontext.Categories.ToList();
                return View("Create", viewModel);
            }
            var course = new Course
            {
                LecturerId = User.Identity.GetUserId(),
                DateTime = viewModel.GetDateTime(),
                CategoryId = viewModel.Category,
                Place = viewModel.Place,
            };
            _dbcontext.Courses.Add(course);
            _dbcontext.SaveChanges();
            return RedirectToAction("Index", "Home");
        }
    }
}

E4BigSchool/Views/Courses/Create.cshtml
@model E4BigSchool.ViewModel.CourseViewModel
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
</head>
<form>
    @using (Html.BeginForm("Create", "Courses"))
    {
        <div class="form-group">
            @Html.LabelFor(m => m.Place, new { @class = "control-label" })
            @Html.TextBoxFor(m => m.Place, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Place)
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.Date, new { @class = "control-label" })
            @Html.TextBoxFor(m => m.Date, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Date)
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.Time, new { @class = "control-label" })
            @Html.TextBoxFor(m => m.Time, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Time)
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.Category)
            @Html.DropDownListFor(m => m.Category,
                 new SelectList(Model.Categories, "Id", "Name"), "", new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Category)
        </div>
        <button type="submit" value="Save" class="btn btn-primary">Save</button>
    }
    @section scripts{
        @Scripts.Render("~/bundles/jqueryval");
    }
    <div class="form-group"></div>
    <div class="form-group"></div>
    <div class="form-group"></div>
    <div class="form-group"></div>

</form>